- id: check-flux-helm-values
  name: Check flux helm values
  description: "Verify that values used by flux HelmReleases are ok."
  entry: python checkHelmValues.py
  language: python
  files: ^[^.].*\.yaml$
